"""added user type

Revision ID: 3352bd42f920
Revises: 5f839a92545e
Create Date: 2025-01-28 18:04:52.769093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3352bd42f920'
down_revision = '5f839a92545e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_type'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_users_user_type_id_user_type'), 'user_type', ['user_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_user_type_id_user_type'), type_='foreignkey')
        batch_op.drop_column('user_type_id')

    op.drop_table('user_type')
    # ### end Alembic commands ###
