"""Add user_types table

Revision ID: 5d327687403b
Revises: cf118ccc1a42
Create Date: 2025-01-29 01:35:10.203523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d327687403b'
down_revision = 'cf118ccc1a42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_types')),
    sa.UniqueConstraint('name', name=op.f('uq_user_types_name'))
    )
    op.drop_table('user_type')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_user_type_id_user_type', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_users_user_type_id_user_types'), 'user_types', ['user_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_user_type_id_user_types'), type_='foreignkey')
        batch_op.create_foreign_key('fk_users_user_type_id_user_type', 'user_type', ['user_type_id'], ['id'])

    op.create_table('user_type',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_user_type'),
    sa.UniqueConstraint('type', name='uq_user_type_type')
    )
    op.drop_table('user_types')
    # ### end Alembic commands ###
