"""password colum added to user

Revision ID: cf118ccc1a42
Revises: 3352bd42f920
Create Date: 2025-01-28 23:56:33.730062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf118ccc1a42'
down_revision = '3352bd42f920'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_type', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_type_type'), ['type'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password')

    with op.batch_alter_table('user_type', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_type_type'), type_='unique')

    # ### end Alembic commands ###
